export const GET_SYNONYMS_PENDING = 'GET_SYNONYMS_PENDING';
export const GET_SYNONYMS_DONE = 'GET_SYNONYMS_DONE';
export const GET_SYNONYMS_ERROR = 'GET_SYNONYMS_ERROR';

export const GET_WORDS_PENDING = 'GET_WORDS_PENDING';
export const GET_WORDS_DONE = 'GET_WORDS_DONE';
export const GET_WORDS_ERROR = 'GET_WORDS_ERROR';
export const CHANGE_WORDS = 'CHANGE_WORDS';
